### ISSUE TITLE
CSS document isn't uploading

### ISSUE THREAD

**Issue by plane-paper** [justsomeblog/justsomeblog.github.io#1]
CSS document isn't uploading. The fifteenth entry's title isn't properly formatted. See:
![image](https://user-images.githubusercontent.com/71282342/156092891-fc221236-623b-46ec-91ae-371d087283fb.png)

**Comment by plane-paper** [comment]
Should be fixed within a few hours

**Comment by RichardRNS** [comment]
Fixed.

**Comment by plane-paper** [comment]
Fixed.

**Comment by plane-paper** [comment]
This is a common issue with github unfortunately.
